/* Auto-generated by tools/build_manifest.py — do not edit */
#ifndef POKEGREEN_ASSETS_MANIFEST_H
#define POKEGREEN_ASSETS_MANIFEST_H

#include <stddef.h>
#include <stdint.h>

#ifndef PG1_ASSET_ENTRY_DEFINED
#define PG1_ASSET_ENTRY_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint32_t size;
    const char* path;
} Pg1AssetEntry;
#endif

#define POKEGREEN_ASSETS_MANIFEST_COUNT 116

static const Pg1AssetEntry POKEGREEN_ASSETS_MANIFEST[POKEGREEN_ASSETS_MANIFEST_COUNT] = {
    { 0x00000000, 0x00000008, "code/rst0.bin" }, /* rst0 bank 00 */
    { 0x00000008, 0x00000008, "code/rst8.bin" }, /* rst8 bank 00 */
    { 0x00000010, 0x00000008, "code/rst10.bin" }, /* rst10 bank 00 */
    { 0x00000018, 0x00000008, "code/rst18.bin" }, /* rst18 bank 00 */
    { 0x00000020, 0x00000008, "code/rst20.bin" }, /* rst20 bank 00 */
    { 0x00000028, 0x00000008, "code/rst28.bin" }, /* rst28 bank 00 */
    { 0x00000030, 0x00000008, "code/rst30.bin" }, /* rst30 bank 00 */
    { 0x00000038, 0x00000008, "code/rst38.bin" }, /* rst38 bank 00 */
    { 0x00000040, 0x00000008, "code/vblank.bin" }, /* vblank bank 00 */
    { 0x00000048, 0x00000008, "code/lcd.bin" }, /* lcd bank 00 */
    { 0x00000050, 0x00000008, "code/timer.bin" }, /* timer bank 00 */
    { 0x00000058, 0x00000008, "code/serial.bin" }, /* serial bank 00 */
    { 0x00000060, 0x00000001, "code/joypad.bin" }, /* joypad bank 00 */
    { 0x00000061, 0x0000005d, "code/high_home.bin" }, /* High Home bank 00 */
    { 0x00000100, 0x00000050, "code/header.bin" }, /* Header bank 00 */
    { 0x00000150, 0x00003e56, "code/home.bin" }, /* Home bank 00 */
    { 0x00004000, 0x00003c49, "code/bank1.bin" }, /* bank1 bank 01 */
    { 0x00008000, 0x0000022e, "audio/sound_effect_headers_1.bin" }, /* Sound Effect Headers 1 bank 02 */
    { 0x0000822e, 0x000000cf, "audio/music_headers_1.bin" }, /* Music Headers 1 bank 02 */
    { 0x000082fd, 0x00000dc9, "audio/sound_effects_1.bin" }, /* Sound Effects 1 bank 02 */
    { 0x000090c6, 0x00000add, "audio/audio_engine_1.bin" }, /* Audio Engine 1 bank 02 */
    { 0x00009ba3, 0x00002451, "audio/music_1.bin" }, /* Music 1 bank 02 */
    { 0x0000c000, 0x00003c4a, "code/bank3.bin" }, /* bank3 bank 03 */
    { 0x00010000, 0x00001380, "gfx/npc_sprites_1.bin" }, /* NPC Sprites 1 bank 04 */
    { 0x00011380, 0x00001558, "gfx/font_graphics.bin" }, /* Font Graphics bank 04 */
    { 0x000128d8, 0x000011c8, "battle/battle_engine_1.bin" }, /* Battle Engine 1 bank 04 */
    { 0x00014000, 0x00003840, "gfx/npc_sprites_2.bin" }, /* NPC Sprites 2 bank 05 */
    { 0x00017840, 0x0000071f, "battle/battle_engine_2.bin" }, /* Battle Engine 2 bank 05 */
    { 0x00018000, 0x00000dee, "maps/maps_1.bin" }, /* Maps 1 bank 06 */
    { 0x00018dee, 0x0000006d, "data/play_time.bin" }, /* Play Time bank 06 */
    { 0x00018e5b, 0x00001585, "maps/maps_2.bin" }, /* Maps 2 bank 06 */
    { 0x0001a3e0, 0x00000338, "maps/doors_and_ledges.bin" }, /* Doors and Ledges bank 06 */
    { 0x0001c000, 0x0000021e, "maps/maps_3.bin" }, /* Maps 3 bank 07 */
    { 0x0001c21e, 0x000007fb, "text/pok_mon_names.bin" }, /* Pokémon Names bank 07 */
    { 0x0001ca19, 0x00001efc, "maps/maps_4.bin" }, /* Maps 4 bank 07 */
    { 0x0001e915, 0x000003ad, "maps/hidden_events_1.bin" }, /* Hidden Events 1 bank 07 */
    { 0x00020000, 0x000002be, "audio/sound_effect_headers_2.bin" }, /* Sound Effect Headers 2 bank 08 */
    { 0x000202be, 0x0000003f, "audio/music_headers_2.bin" }, /* Music Headers 2 bank 08 */
    { 0x000202fd, 0x00001071, "audio/sound_effects_2.bin" }, /* Sound Effects 2 bank 08 */
    { 0x0002136e, 0x0000005a, "audio/low_health_alarm_audio_engine_2.bin" }, /* Low Health Alarm (Audio Engine 2) bank 08 */
    { 0x000213c8, 0x000004b1, "data/bill_s_pc.bin" }, /* Bill's PC bank 08 */
    { 0x00021879, 0x00000aa9, "audio/audio_engine_2.bin" }, /* Audio Engine 2 bank 08 */
    { 0x00022322, 0x00001c30, "audio/music_2.bin" }, /* Music 2 bank 08 */
    { 0x00024000, 0x00003d6b, "gfx/pics_1.bin" }, /* Pics 1 bank 09 */
    { 0x00027d6b, 0x0000024d, "battle/battle_engine_3.bin" }, /* Battle Engine 3 bank 09 */
    { 0x00028000, 0x00003ea9, "gfx/pics_2.bin" }, /* Pics 2 bank 0a */
    { 0x0002bea9, 0x00000053, "battle/battle_engine_4.bin" }, /* Battle Engine 4 bank 0a */
    { 0x0002c000, 0x00003b7b, "gfx/pics_3.bin" }, /* Pics 3 bank 0b */
    { 0x0002fb7b, 0x000003c1, "battle/battle_engine_5.bin" }, /* Battle Engine 5 bank 0b */
    { 0x00030000, 0x00003f2b, "gfx/pics_4.bin" }, /* Pics 4 bank 0c */
    { 0x00033f2b, 0x00000065, "battle/battle_engine_6.bin" }, /* Battle Engine 6 bank 0c */
    { 0x00034000, 0x00003244, "gfx/pics_5.bin" }, /* Pics 5 bank 0d */
    { 0x00037244, 0x00000c44, "data/slot_machines.bin" }, /* Slot Machines bank 0d */
    { 0x00038000, 0x00003be6, "battle/battle_engine_7.bin" }, /* Battle Engine 7 bank 0e */
    { 0x0003c000, 0x00003bc8, "battle/battle_core.bin" }, /* Battle Core bank 0f */
    { 0x00040000, 0x000027f3, "code/bank10.bin" }, /* bank10 bank 10 */
    { 0x00044000, 0x00000169, "maps/maps_5.bin" }, /* Maps 5 bank 11 */
    { 0x00044169, 0x000000e8, "text/pok_dex_rating.bin" }, /* Pokédex Rating bank 11 */
    { 0x00044251, 0x00002730, "maps/maps_6.bin" }, /* Maps 6 bank 11 */
    { 0x00046981, 0x0000072a, "maps/hidden_events_core.bin" }, /* Hidden Events Core bank 11 */
    { 0x00048000, 0x000000eb, "maps/maps_7.bin" }, /* Maps 7 bank 12 */
    { 0x000480eb, 0x00000067, "maps/screen_effects.bin" }, /* Screen Effects bank 12 */
    { 0x00048152, 0x0000223d, "maps/maps_8.bin" }, /* Maps 8 bank 12 */
    { 0x0004c000, 0x00003d04, "gfx/trainer_pics.bin" }, /* Trainer Pics bank 13 */
    { 0x0004fd04, 0x000000a1, "maps/maps_9.bin" }, /* Maps 9 bank 13 */
    { 0x0004fda5, 0x000001fd, "data/predefs.bin" }, /* Predefs bank 13 */
    { 0x00050000, 0x000025af, "maps/maps_10.bin" }, /* Maps 10 bank 14 */
    { 0x000525af, 0x000000c4, "battle/battle_engine_8.bin" }, /* Battle Engine 8 bank 14 */
    { 0x00052673, 0x000003cf, "maps/hidden_events_2.bin" }, /* Hidden Events 2 bank 14 */
    { 0x00054000, 0x0000124f, "maps/maps_11.bin" }, /* Maps 11 bank 15 */
    { 0x0005524f, 0x00000294, "battle/battle_engine_9.bin" }, /* Battle Engine 9 bank 15 */
    { 0x000554e3, 0x000011ff, "maps/maps_12.bin" }, /* Maps 12 bank 15 */
    { 0x000566e2, 0x00000117, "data/diploma.bin" }, /* Diploma bank 15 */
    { 0x000567f9, 0x00000252, "data/trainer_sight.bin" }, /* Trainer Sight bank 15 */
    { 0x00058000, 0x00000d99, "maps/maps_13.bin" }, /* Maps 13 bank 16 */
    { 0x00058d99, 0x00000317, "battle/battle_engine_10.bin" }, /* Battle Engine 10 bank 16 */
    { 0x000590b0, 0x000014ef, "maps/maps_14.bin" }, /* Maps 14 bank 16 */
    { 0x0005a59f, 0x0000001c, "data/saffron_guards.bin" }, /* Saffron Guards bank 16 */
    { 0x0005c000, 0x000000dc, "maps/maps_15.bin" }, /* Maps 15 bank 17 */
    { 0x0005c0dc, 0x0000000f, "text/starter_dex.bin" }, /* Starter Dex bank 17 */
    { 0x0005c0eb, 0x00001a73, "maps/maps_16.bin" }, /* Maps 16 bank 17 */
    { 0x0005db5e, 0x000003b7, "maps/hidden_events_3.bin" }, /* Hidden Events 3 bank 17 */
    { 0x00060000, 0x00001006, "maps/maps_17.bin" }, /* Maps 17 bank 18 */
    { 0x00061006, 0x000000fb, "data/cinnabar_lab_fossils.bin" }, /* Cinnabar Lab Fossils bank 18 */
    { 0x00061101, 0x00001318, "maps/maps_18.bin" }, /* Maps 18 bank 18 */
    { 0x00062419, 0x00000111, "maps/hidden_events_4.bin" }, /* Hidden Events 4 bank 18 */
    { 0x00064000, 0x00003fe0, "gfx/tilesets_1.bin" }, /* Tilesets 1 bank 19 */
    { 0x00068000, 0x0000006f, "battle/battle_engine_11.bin" }, /* Battle Engine 11 bank 1a */
    { 0x0006806f, 0x00003f80, "gfx/tilesets_2.bin" }, /* Tilesets 2 bank 1a */
    { 0x0006c000, 0x00004000, "gfx/tilesets_3.bin" }, /* Tilesets 3 bank 1b */
    { 0x00070000, 0x00003b9d, "code/bank1c.bin" }, /* bank1C bank 1c */
    { 0x00074000, 0x0000005c, "maps/maps_19.bin" }, /* Maps 19 bank 1d */
    { 0x0007405c, 0x00000817, "data/itemfinder_1.bin" }, /* Itemfinder 1 bank 1d */
    { 0x00074873, 0x0000066e, "maps/maps_20.bin" }, /* Maps 20 bank 1d */
    { 0x00074ee1, 0x0000012c, "data/vending_machine.bin" }, /* Vending Machine bank 1d */
    { 0x0007500d, 0x00001572, "maps/maps_21.bin" }, /* Maps 21 bank 1d */
    { 0x0007657f, 0x000002fd, "data/itemfinder_2.bin" }, /* Itemfinder 2 bank 1d */
    { 0x00078000, 0x00003fc0, "code/bank1e.bin" }, /* bank1E bank 1e */
    { 0x0007c000, 0x00000249, "audio/sound_effect_headers_3.bin" }, /* Sound Effect Headers 3 bank 1f */
    { 0x0007c249, 0x000000b4, "audio/music_headers_3.bin" }, /* Music Headers 3 bank 1f */
    { 0x0007c2fd, 0x00000e3e, "audio/sound_effects_3.bin" }, /* Sound Effects 3 bank 1f */
    { 0x0007d13b, 0x00000a80, "audio/audio_engine_3.bin" }, /* Audio Engine 3 bank 1f */
    { 0x0007dbbb, 0x0000243f, "audio/music_3.bin" }, /* Music 3 bank 1f */
    { 0x00080000, 0x00002aaf, "text/text_1.bin" }, /* Text 1 bank 20 */
    { 0x00084000, 0x00002ca1, "text/text_2.bin" }, /* Text 2 bank 21 */
    { 0x00088000, 0x00002cf9, "text/text_3.bin" }, /* Text 3 bank 22 */
    { 0x0008c000, 0x00002c09, "text/text_4.bin" }, /* Text 4 bank 23 */
    { 0x00090000, 0x00002903, "text/text_5.bin" }, /* Text 5 bank 24 */
    { 0x00094000, 0x00002a38, "text/text_6.bin" }, /* Text 6 bank 25 */
    { 0x00098000, 0x00002b7b, "text/text_7.bin" }, /* Text 7 bank 26 */
    { 0x0009c000, 0x00002aa4, "text/text_8.bin" }, /* Text 8 bank 27 */
    { 0x000a0000, 0x00002a37, "text/text_9.bin" }, /* Text 9 bank 28 */
    { 0x000a4000, 0x00002b94, "text/text_10.bin" }, /* Text 10 bank 29 */
    { 0x000a8000, 0x00000330, "text/text_11.bin" }, /* Text 11 bank 2a */
    { 0x000ac000, 0x00003838, "text/pok_dex_text.bin" }, /* Pokédex Text bank 2b */
    { 0x000b0000, 0x0000060f, "text/move_names.bin" }, /* Move Names bank 2c */
};

#endif
