/* Generated by gbrecomp */
#ifndef pokegreen_H
#define pokegreen_H

#include "gbrt.h"

const GBConfig* pokegreen_default_config(void);
void pokegreen_run(GBContext* ctx);
void pokegreen_init(GBContext* ctx);
int pokegreen_main(int argc, char* argv[]);

/* SHA-256 of the input ROM at generation time. Launchers extern
 * this and pass it to gb_sha256_verify_file() to detect ROM-dump
 * mismatches. */
extern const char expected_sha256[65];

#endif
